### ISSUE TITLE
Installation and usage instructions

### ISSUE THREAD

**Issue by oojacoboo** [buckyroberts/Ella#4]
Hey, looked through the source a bit and didn't see any API keys, configs, etc.

Is everything hard coded?  It'd be great if you could update the README to include details on installation and usage.

Executing the main.py gives me a SyntaxError:

```
Traceback (most recent call last):
  File "./main.py", line 1, in <module>
    from models.brain import Brain
  File "/Volumes/repos/Ella/models/brain.py", line 2, in <module>
    from models.condition import Condition
  File "/Volumes/repos/Ella/models/condition.py", line 15
    return f"{self.attribute} {operator_to_str(self.operator)} {self.value}"
                                                                           ^
SyntaxError: invalid syntax
```

Is there a minimum required version of python?

**Comment by sqro2** [comment]
Is there a minimum required version of python?
Python 3.6 (or newer) required (included in Readme.md file)

yes I agree to the fact that there should be detailed uses guide for beginners.

**Comment by buckyroberts** [comment]
No API key required, it uses all public API endpoints. Also in the README it states Python 3.6 (or newer) required.

**Comment by oojacoboo** [comment]
Thanks, I see that now.  It'd be nice to add a requirements and installation sections.  Those are far more common and generally at the top of the readme, due to importance.

**Comment by buckyroberts** [comment]
Good thinking @oojacoboo , I will update it on my next commit!
